// Adjective + animal pool for auto-generated nicknames. Both lists are
// hand-curated to keep every combination short enough for the 24-char limit
// in validation.ts and to stay clear of the profanity blocklist.
//
// Constraints when extending:
//   - lower-case, ASCII letters only (validation rejects control chars)
//   - keep each word ≤ 10 chars so adj+space+animal ≤ ~21 chars
//   - no profanity substrings (cross-check with validation.ts blocklist)

export const ADJECTIVES = [
  'brave',
  'breezy',
  'bubbly',
  'clever',
  'cosmic',
  'crisp',
  'daring',
  'dapper',
  'dizzy',
  'eager',
  'electric',
  'fearless',
  'feisty',
  'fluffy',
  'fuzzy',
  'gentle',
  'glowing',
  'golden',
  'grumpy',
  'happy',
  'humble',
  'jolly',
  'lucky',
  'mellow',
  'merry',
  'mighty',
  'moonlit',
  'neon',
  'nimble',
  'noble',
  'plucky',
  'quiet',
  'rapid',
  'rare',
  'rowdy',
  'rustic',
  'sassy',
  'scrappy',
  'silent',
  'silly',
  'sleek',
  'sleepy',
  'snazzy',
  'spicy',
  'stormy',
  'sunny',
  'swift',
  'thrifty',
  'tiny',
  'vivid',
  'witty',
  'woolly',
  'zealous',
  'zippy',
] as const;

export const ANIMALS = [
  'badger',
  'bear',
  'beetle',
  'bison',
  'bunny',
  'cheetah',
  'chicken',
  'cobra',
  'crab',
  'crane',
  'deer',
  'dingo',
  'dolphin',
  'dove',
  'dragon',
  'duck',
  'eagle',
  'falcon',
  'ferret',
  'finch',
  'fox',
  'frog',
  'gecko',
  'giraffe',
  'goat',
  'goose',
  'hare',
  'hawk',
  'hedgehog',
  'heron',
  'hippo',
  'horse',
  'ibex',
  'iguana',
  'jaguar',
  'koala',
  'lemur',
  'leopard',
  'lion',
  'llama',
  'lobster',
  'lynx',
  'magpie',
  'marmot',
  'mole',
  'moose',
  'narwhal',
  'newt',
  'otter',
  'owl',
  'panda',
  'panther',
  'parrot',
  'penguin',
  'pony',
  'possum',
  'puffin',
  'quail',
  'rabbit',
  'raccoon',
  'raven',
  'salmon',
  'seal',
  'shark',
  'sheep',
  'skunk',
  'sloth',
  'snail',
  'sparrow',
  'spider',
  'squid',
  'stoat',
  'swan',
  'tapir',
  'tiger',
  'toad',
  'turkey',
  'turtle',
  'viper',
  'vole',
  'walrus',
  'weasel',
  'whale',
  'wolf',
  'wombat',
  'yak',
  'zebra',
] as const;

export interface GenerateNicknameOptions {
  /** RNG returning a number in [0, 1). Defaults to Math.random. */
  random?: () => number;
}

function pick<T>(list: readonly T[], random: () => number): T {
  const idx = Math.floor(random() * list.length);
  return list[idx] as T;
}

export function generateNickname(options: GenerateNicknameOptions = {}): string {
  const random = options.random ?? Math.random;
  const adj = pick(ADJECTIVES, random);
  const animal = pick(ANIMALS, random);
  return `${adj} ${animal}`;
}
